### ISSUE TITLE
user-can-view-list-of-parks

### ISSUE THREAD

**Issue by brendatrieu** [brendatrieu/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view a list of all national parks in alphabetical order.

## 📐 Functionality

Create a responsive page with a photo of the park, a description, filter bar, favorite icon,  and get routed to more info, if desired.

## 🖼️ Wireframes

![issue-1-view-parks](https://user-images.githubusercontent.com/121825299/224108195-3bbcb04e-0cfc-4da7-8f57-dbfc5747f3a0.png)

## ✅ Task List

- [x] Create a nav bar 
- [x] Create HTML for fixed fields (i.e. page header, filter bar)
- [x] Create HTML with dummy data for first park
    - [x]  Write CSS for mobile devices first.
    - [x]  Adjust styling to be responsive on desktops
- [x] Create JS to render first 10 parks
    - [x] Make API request to grab all national parks
    - [x] Create reusable function to render HTML for each park 
        - [x] Loop over park data to fill in each image, title, description
        - [x] Use data to assign id attribute to divs using park IDs
- [x] Create JS to render based on page number
    - [x]  Calculate which index of the database would appear based on page number
       - [x]  Call function to render elements with targeted parks
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that there are no errors or logs in the console while using the application.
  - [x] Test functionality and user interface in private browsing mode.
  - [x] Fix all errors.
