### ISSUE TITLE
user-can-clear-filters

### ISSUE THREAD

**Issue by brendatrieu** [brendatrieu/ajax-project#11]
## ⚙️ Feature

Users can clear all selected filters.

## 📐 Functionality

Create a 'Clear All' button that will uncheck any selected filters.

## 🖼️ Wireframes

![issue-6-clear-filters-desktop](https://user-images.githubusercontent.com/121825299/224117983-b291dca0-1839-40a8-aa5c-be71205892bc.png)

![issue-6-clear-filters-mobile](https://user-images.githubusercontent.com/121825299/224117998-52965f86-d1a3-4f34-877a-98ca4ac5b88e.png)

## ✅ Task List

- [x] Modify search button function to keep filters previously selected.
  - [x]  Ensure fields remain selected upon page refresh
  - [x]  Update view swapping function to reset the filter form when users switch pages.
- [x] Create HTML and CSS for 'Clear All' button.
  - [x]  Update media query to make the 'Clear All' and 'Search' buttons responsive to mobile and desktop views.
- [x] Create an event listener to react to the 'Clear All' button clicks.
  - [x]  Unselect all filters that were previously selected.
  - [x]  Update inputs object to clear all values.
- [x] Make sure that all click target shows a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all console logs and clear errors from the console.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that all previous functionality still works without errors.
