### ISSUE TITLE
user-can-view-park-details

### ISSUE THREAD

**Issue by brendatrieu** [brendatrieu/ajax-project#2]
## ⚙️ Feature

Users can view details on individual parks.

## 📐 Functionality

Create a button that will route users to an individual park's page to see additional information. Design a park page with park details and the favorite icon.

## 🖼️ Wireframes

![issue-2-view-park-details](https://user-images.githubusercontent.com/121825299/224112255-9c457f98-d04b-46fa-b719-7be9405d31e0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x]  Create a new section for the individual park view.
- [x]  Define a view swapping function to go from 'home-page' to 'individual-park'.
- [x]  Input dummy data to fill page for an individual park.
- [x]  Create CSS to match overall application theme and to be responsive to mobile and desktop devices.
- [x]  Create an event listener for 'more info' buttons to route to the individual park page
  - [x]  Save the ID of the targeted park in the data object
- [x]  Define a function to update elements on the page based on the data of the targeted park.
  - [x]  Create an XMLHttpRequest filtered on the ID of the park
  - [x]  Query the DOM for each element that will be updated 
  - [x]  Query the API object and assign the appropriate data to each element.
- [x]  Add an event listener on the title of the nav bar to swap views back to the home-page.
  - [x]  Reset the page form to page 1.
  - [x]  Update the view property of the data object to be 'home-page'.
- **Clean Up**
  - [x]  Remove all console logs and clear errors from the console.
  - [x]  Remove all commented out code.
  - [x]  Remove all CSS properties that have no effect.
  - [x]  Confirm that all previous functionality still works without errors.
