### ISSUE TITLE
user-can-favorite-park

### ISSUE THREAD

**Issue by brendatrieu** [brendatrieu/ajax-project#3]
## ⚙️ Feature

Users can favorite parks to they'd like to visit.

## 📐 Functionality

Enable a function for favorite icons where users can favorite parks and keep track of them. Create a page to display all the favorited parks.

## 🖼️ Wireframes
![issue-3-favorite-parks-desktop](https://user-images.githubusercontent.com/121825299/224112990-b5a7294e-0328-49eb-bb69-fa2119900cef.png)

![issue-3-favorite-park-mobile](https://user-images.githubusercontent.com/121825299/224113008-591ca149-ab88-4950-8398-1263d039526b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

  - [x]  Create HTML and CSS for favorites section.
    - [x]  Ensure favorites section is responsive to mobile and desktop devices.
  - [x] Create function to keep users on the same page if they refresh.
  - [x]  Create a function to route users to the home page when they close the browser and reopen.
  - [x]  Add functionality to star favicons to save the target park to a favorites list on the local storage.
  - [x]  Create a function to toggle star fill when clicked.
  - [x]  Update view swapping function to swap to a favorite section.
    - [x]  Add an event listener to the 'Favorites' link to run view swapping function to the favorite section.
    - [x]  Ensure users will remain on the Favorites page if they refresh the page.
    - [x]  Update API creation function to query API based on set list of parks.
    - [x]  Load parks based on favorites list.
  - [x]  Create a function to check whether displayed park(s) are on the favorites list and adjust the star favicon fill depending on status.
  - [x]  Create section to display when there are no favorites.
    - [x] Update view swapping function to toggle 'no favorites' message.
    - [x]  Create a button to route users back to the home page to look for more parks.
  - [x]  Update page number footer to display total number of pages based on view.
  - **Clean Up**
  - [x]  Remove all console logs and clear errors from the console.
  - [x]  Remove all commented out code.
  - [x]  Remove all CSS properties that have no effect.
  - [x]  Confirm that all previous functionality still works without errors.
