### ISSUE TITLE
users-can-unfavorite-parks

### ISSUE THREAD

**Issue by brendatrieu** [brendatrieu/ajax-project#4]
## ⚙️ Feature

Users can remove parks from their favorites list.

## 📐 Functionality

Create a function to remove parks from users' favorites lists and update their favorites page.

## 🖼️ Wireframes
![issue-3-favorite-parks-desktop](https://user-images.githubusercontent.com/121825299/224113259-9c0b03d3-7713-45f2-921d-b346d45956fe.png)
![issue-3-favorite-park-mobile](https://user-images.githubusercontent.com/121825299/224113279-a80f868e-aee6-47d5-8c43-ec93e3fa8672.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Define a function to remove parks from the favorites list when they are unsaved.
  - [x] Ensure the favorites section reflects the deletion.
  - [x]  Create a function to show the 'no favorites' message when all favorited parks have been unsaved.
  - [x] Ensure star favicon of the corresponding park is styled appropriately in other parts of the app 
- **Clean Up**
  - [x] Remove all console logs and clear errors from the console.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that all previous functionality still works without errors.
