### ISSUE TITLE
user-can-filter-parks

### ISSUE THREAD

**Issue by brendatrieu** [brendatrieu/ajax-project#5]
## ⚙️ Feature

Allow users to reduce the park lists across the parks home page and favorites page.

## 📐 Functionality

Create a filter modal that will appear when the filter icon is clicked on, allowing users to search by various fields.

## 🖼️ Wireframes
![issue-5-filter-parks-home-desktop](https://user-images.githubusercontent.com/121825299/224117594-c1842bac-30e8-4393-807e-f9ff83ace0fb.png)
![issue-5-filter-parks-fav-desktop](https://user-images.githubusercontent.com/121825299/224117617-d6336904-7f27-4de5-905b-0e557a9f114f.png)
![issue-5-filter-parks-home-mobile](https://user-images.githubusercontent.com/121825299/224117632-7a9b82ef-91c5-41d7-8c9d-c8d6666676d3.png)
![issue-5-filter-parks-fav-mobile](https://user-images.githubusercontent.com/121825299/224117639-4c4c6082-06d1-49e3-8fdc-612cb9da886a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a HTML and CSS for drop down menus.
  - [x] Define a function to create an option for each field in the drop down menu
  - [x]  Add an event listener on the filter bar and the submit button to toggle the display of the filter form
  - [x]  Add an event listener to each drop down to toggle the display of options.
  - [x]  Add an event listener to collect inputs from the form upon submit
- [x] Define a function to compile inputs and transform into usable parameters
- [x]  Define a function to query APIs and return parks with all criteria met.
- [x]  Render parks depending based on results
  - [x] Create HTML and CSS to display when no parks meet all the criteria.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x]  Update filter function to search appropriately based on home-page view vs favorites view.
- **Clean Up**
  - [x] Remove all console logs and clear errors from the console.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that all previous functionality still works without errors.
